---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---

```{r, message=FALSE, warning = FALSE, error=FALSE}
library(tidyverse)
# loading in
A_Greener_Future_Data_2014 <- read_csv("AGFDATA - 2014 - A Greener Future Data 20.csv")
A_Greener_Future_Data_2015 <- read_csv("AGFDATA - 2015 - A Greener Future Data 20.csv")
A_Greener_Future_Data_2016 <- read_csv("AGFDATA - 2016 - A Greener Future Data 20.csv")
A_Greener_Future_Data_2017 <- read_csv("AGFDATA - 2017 - A Greener Future Data 20.csv")
A_Greener_Future_Data_2018 <- read_csv("AGFDATA - 2018 - A Greener Future Data 20.csv")
A_Greener_Future_Data_2019 <- read_csv("AGFDATA - 2019 - A Greener Future Data 20.csv")


# fixing column names
names(A_Greener_Future_Data_2014) <- A_Greener_Future_Data_2014[1,]
A_Greener_Future_Data_2014 <-A_Greener_Future_Data_2014[-1,]

names(A_Greener_Future_Data_2015) <- A_Greener_Future_Data_2015[1,]
A_Greener_Future_Data_2015 <-A_Greener_Future_Data_2015[-1,]

names(A_Greener_Future_Data_2016) <- A_Greener_Future_Data_2016[1,]
A_Greener_Future_Data_2016 <-A_Greener_Future_Data_2016[-1,]

names(A_Greener_Future_Data_2017) <- A_Greener_Future_Data_2017[1,]
A_Greener_Future_Data_2017 <-A_Greener_Future_Data_2017[-1,]

names(A_Greener_Future_Data_2018) <- A_Greener_Future_Data_2018[1,]
A_Greener_Future_Data_2018 <-A_Greener_Future_Data_2018[-1,]

names(A_Greener_Future_Data_2019) <- A_Greener_Future_Data_2019[1,]
A_Greener_Future_Data_2019 <-A_Greener_Future_Data_2019[-1,]

# binding
AGF_2014_19 <- rbind(A_Greener_Future_Data_2014, A_Greener_Future_Data_2015, A_Greener_Future_Data_2016, A_Greener_Future_Data_2017, A_Greener_Future_Data_2018, A_Greener_Future_Data_2019)

library(lubridate)
library(janitor)
# converting column types into numeric, fixing names into snake_case, and parsing the date
AGF_2014_19 <- AGF_2014_19 %>%
  mutate_at(names(AGF_2014_19[,15:44]), as.numeric) %>%
  clean_names() %>%
  mutate(Date_full = parse_date(date, format = '%B %d, %Y'),
         Date_half = parse_date(date, format = '%b %d, %Y'),
         date = coalesce(Date_full, Date_half),
         volunteers = as.numeric(volunteers),
         event = ifelse(event == "5 Pieces a Day", "5 Piece Challenge", event)
) %>%
  drop_na(date) %>%
  select(-Date_full, -Date_half) 

AGF_2014_19$latitude[AGF_2014_19$city == "Thunder Bay" & AGF_2014_19$date == "2018-05-05"] <- -89.194652

AGF_2014_19$longitude[AGF_2014_19$city == "Thunder Bay" & AGF_2014_19$date == "2018-05-05"] <- 48.458982

unique(AGF_2014_19$event)
```

Weekdays for cig butts
```{r}
# these could use groupings (ie. plastic, metal)
AGF_2014_19 %>%
  mutate(weekday = wday(date)) %>%
  group_by(weekday) %>%
  select(-longitude, -latitude,-location, -city, -province, -country, -photos, -sponsor, -coordinator, -volunteers, -strange_items) %>%
  summarize(cigarette_butts = sum(cigarette_butts, na.rm = T),
            tobacco_packaging = sum(tobacco_packaging, na.rm = T),
            lighters = sum(lighters, na.rm = T),
            paper_bags = sum(paper_bags, na.rm = T),
            reusable_bags = sum(reusable_bags, na.rm = T),
            food_wrappers = sum(food_wrappers, na.rm = T),
            plastic_beverage_bottles = sum(plastic_beverage_bottles, na.rm = T),
            plastic_bottle_caps = sum(plastic_bottle_caps, na.rm = T),
            metal_bottle_caps = sum(metal_bottle_caps, na.rm = T),
            cans = sum(cans, na.rm = T),
            glass_bottles = sum(glass_bottles, na.rm = T),
            straws = sum(straws, na.rm = T),
            utensils = sum(utensils, na.rm = T),
            personal_hygiene = sum(personal_hygiene, na.rm = T),
            clothing = sum(clothing, na.rm = T),
            construction = sum(construction, na.rm = T),
            fishing = sum(fishing, na.rm = T),
            plastic_pieces = sum(plastic_pieces, na.rm = T),
            paper = sum(paper, na.rm = T),
            glass = sum(glass, na.rm = T),
            foam = sum(foam, na.rm = T),
            other = sum(other, na.rm = T),
            syringes = sum(syringes, na.rm = T),
            total = sum(total, na.rm = T)) %>%
  gather(item, value, -weekday, -total) %>%
  filter(item != "cigarette_butts") %>%

ggplot(aes(x=weekday, y=value, fill = item, group = weekday)) +
  geom_col() +
  scale_y_continuous(labels = scales::comma_format())
```

Cumulative Charts 
```{r}
# non cigarette butt collection over the summer 2016
AGF_2014_19 %>%
  filter(date >= "2018-05-01" & date <= "2018-09-01") %>%
  arrange(date) %>%
    mutate(total = total - cigarette_butts,
      cumulative = cumsum(total)) %>%
    ggplot(aes(x=date, y=cumulative, frame = date)) +
    geom_line() +
    scale_y_continuous(labels = scales::comma_format()) 

# with cigarete butts (what an event they have eh)
AGF_2014_19 %>%
  filter(date >= "2018-05-01" & date <= "2018-09-01") %>%
  arrange(date) %>%
    mutate(cumulative = cumsum(total)) %>%
    ggplot(aes(x=date, y=cumulative, frame = date)) +
    geom_line() +
    scale_y_continuous(labels = scales::comma_format()) 
```

Average metrics
```{r}
saturdays <- AGF_2014_19 %>%
  mutate(weekday = wday(date),
         saturday = weekday == 7) %>%
  filter(saturday == T) 


# avreage amount collected on saturdays since inception - 7105
  saturdays %>%
    summarize(saturday_average = sum(total, na.rm=T)/(52*5 + as.numeric(today()-as.Date("2019-01-01")) %/% 7))

  
# average amount collected daily since inception ~500 pieces a day
  AGF_2014_19 %>%
    summarize(daily_avg = sum(total, na.rm=T)/(365*5 + as.numeric(today()-as.Date("2019-01-01"))))

```

Event Data of Ontario
```{r}
# number of volunteers by event
AGF_2014_19 %>%
  group_by(event) %>%
  summarize(total = sum(as.numeric(volunteers), na.rm=T)) %>%
  arrange(-total)

# Love Your Lake by city
AGF_2014_19 %>%
  filter(event == "Love Your Lake") %>%
  group_by(city) %>%
  summarize(cigarette_butts = sum(as.numeric(cigarette_butts), na.rm = T),
            tobacco_packaging = sum(as.numeric(tobacco_packaging), na.rm = T),
            lighters = sum(as.numeric(lighters), na.rm = T),
            paper_bags = sum(as.numeric(paper_bags), na.rm = T),
            reusable_bags = sum(as.numeric(reusable_bags), na.rm = T),
            food_wrappers = sum(as.numeric(food_wrappers), na.rm = T),
            plastic_beverage_bottles = sum(as.numeric(plastic_beverage_bottles), na.rm = T),
            plastic_bottle_caps = sum(as.numeric(plastic_bottle_caps), na.rm = T),
            metal_bottle_caps = sum(as.numeric(metal_bottle_caps), na.rm = T),
            cans = sum(as.numeric(cans), na.rm = T),
            glass_bottles = sum(as.numeric(glass_bottles), na.rm = T),
            straws = sum(as.numeric(straws), na.rm = T),
            utensils = sum(as.numeric(utensils), na.rm = T),
            personal_hygiene = sum(as.numeric(personal_hygiene), na.rm = T),
            clothing = sum(as.numeric(clothing), na.rm = T),
            construction = sum(as.numeric(construction), na.rm = T),
            fishing = sum(as.numeric(fishing), na.rm = T),
            plastic_pieces = sum(as.numeric(plastic_pieces), na.rm = T),
            paper = sum(as.numeric(paper), na.rm = T),
            glass = sum(as.numeric(glass), na.rm = T),
            foam = sum(as.numeric(foam), na.rm = T),
            other = sum(as.numeric(other), na.rm = T),
            syringes = sum(as.numeric(syringes), na.rm = T),
            total = sum(as.numeric(total), na.rm = T))

# Butt blitz by city
AGF_2014_19 %>%
  filter(event == "The Butt Blitz") %>%
  group_by(city) %>%
  summarize(cigarette_butts = sum(as.numeric(cigarette_butts), na.rm = T))
```
Provinces (Ontario)
```{r}
# number of volunteers by province - over 1000 volunteers from ontario
AGF_2014_19 %>%
  group_by(province) %>%
  summarize(total = sum(as.numeric(volunteers), na.rm=T)) %>%
  arrange(-total)

# number of trash picked up by province
AGF_2014_19 %>%
  group_by(province) %>%
  filter(!province %in% c("New Providence", "New York", NA)) %>%
  summarize(cigarette_butts = sum(as.numeric(cigarette_butts), na.rm = T)) %>%
  arrange(-cigarette_butts)

## Cities in Ontario - 73 cities 
AGF_2014_19 %>%
  filter(province == "Ontario") %>%
  count(city)

# 331 days for events
AGF_2014_19 %>%
  filter(province == "Ontario") %>%
  count(date) %>%
  count(date) %>%
  summarize(total_days = sum(nn))

# number of volunteers by city
AGF_2014_19 %>%
  filter(province == "Ontario") %>%
  group_by(city) %>%
  summarize(volunteers = sum(volunteers, na.rm=T)) %>%
  arrange(-volunteers)
```
wordclouds by Ontario & Canada-wide
```{r}
library(wordcloud2)

# based on number of events
AGF_2014_19 %>%
  filter(province == "Ontario") %>%
  count(city) %>%
wordcloud2(fontFamily = "Ubuntu", color = rep(c("222D4D", "B2C88B"),20), backgroundColor = "F2F2F2")

# based on number of volunteers
AGF_2014_19 %>%
  filter(province == "Ontario") %>%
  group_by(city) %>%
  summarize(volunteers = sum(volunteers, na.rm=T)) %>%
wordcloud2(fontFamily = "Ubuntu", color = rep(c("222D4D", "B2C88B"),20), backgroundColor = "F2F2F2")

# based on total trash picked up
AGF_2014_19 %>%
  filter(province == "Ontario") %>%
  group_by(city) %>%
  summarize(total = sum(total, na.rm=T)) %>%
wordcloud2(fontFamily = "Ubuntu", color = rep(c("222D4D", "B2C88B"),20), backgroundColor = "F2F2F2")

# across canada total trash
AGF_2014_19 %>%
  group_by(city) %>%
  summarize(total = sum(total, na.rm=T)) %>%
wordcloud2(fontFamily = "Ubuntu", color = rep(c("222D4D", "B2C88B"),20), backgroundColor = "F2F2F2")
```

```{r}
# looking at each city
AGF_2014_19 %>%
  group_by(city) %>%
  summarize(cigarette_butts = sum(as.numeric(cigarette_butts), na.rm = T),
            tobacco_packaging = sum(as.numeric(tobacco_packaging), na.rm = T),
            lighters = sum(as.numeric(lighters), na.rm = T),
            paper_bags = sum(as.numeric(paper_bags), na.rm = T),
            reusable_bags = sum(as.numeric(reusable_bags), na.rm = T),
            food_wrappers = sum(as.numeric(food_wrappers), na.rm = T),
            plastic_beverage_bottles = sum(as.numeric(plastic_beverage_bottles), na.rm = T),
            plastic_bottle_caps = sum(as.numeric(plastic_bottle_caps), na.rm = T),
            metal_bottle_caps = sum(as.numeric(metal_bottle_caps), na.rm = T),
            cans = sum(as.numeric(cans), na.rm = T),
            glass_bottles = sum(as.numeric(glass_bottles), na.rm = T),
            straws = sum(as.numeric(straws), na.rm = T),
            utensils = sum(as.numeric(utensils), na.rm = T),
            personal_hygiene = sum(as.numeric(personal_hygiene), na.rm = T),
            clothing = sum(as.numeric(clothing), na.rm = T),
            construction = sum(as.numeric(construction), na.rm = T),
            fishing = sum(as.numeric(fishing), na.rm = T),
            plastic_pieces = sum(as.numeric(plastic_pieces), na.rm = T),
            paper = sum(as.numeric(paper), na.rm = T),
            glass = sum(as.numeric(glass), na.rm = T),
            foam = sum(as.numeric(foam), na.rm = T),
            other = sum(as.numeric(other), na.rm = T),
            syringes = sum(as.numeric(syringes), na.rm = T),
            total = sum(as.numeric(total), na.rm = T)) %>%
  arrange(-total)

# by events
AGF_2014_19 %>%
  group_by(event) %>%
  summarize(cigarette_butts = sum(as.numeric(cigarette_butts), na.rm = T),
            tobacco_packaging = sum(as.numeric(tobacco_packaging), na.rm = T),
            lighters = sum(as.numeric(lighters), na.rm = T),
            paper_bags = sum(as.numeric(paper_bags), na.rm = T),
            reusable_bags = sum(as.numeric(reusable_bags), na.rm = T),
            food_wrappers = sum(as.numeric(food_wrappers), na.rm = T),
            plastic_beverage_bottles = sum(as.numeric(plastic_beverage_bottles), na.rm = T),
            plastic_bottle_caps = sum(as.numeric(plastic_bottle_caps), na.rm = T),
            metal_bottle_caps = sum(as.numeric(metal_bottle_caps), na.rm = T),
            cans = sum(as.numeric(cans), na.rm = T),
            glass_bottles = sum(as.numeric(glass_bottles), na.rm = T),
            straws = sum(as.numeric(straws), na.rm = T),
            utensils = sum(as.numeric(utensils), na.rm = T),
            personal_hygiene = sum(as.numeric(personal_hygiene), na.rm = T),
            clothing = sum(as.numeric(clothing), na.rm = T),
            construction = sum(as.numeric(construction), na.rm = T),
            fishing = sum(as.numeric(fishing), na.rm = T),
            plastic_pieces = sum(as.numeric(plastic_pieces), na.rm = T),
            paper = sum(as.numeric(paper), na.rm = T),
            glass = sum(as.numeric(glass), na.rm = T),
            foam = sum(as.numeric(foam), na.rm = T),
            other = sum(as.numeric(other), na.rm = T),
            syringes = sum(as.numeric(syringes), na.rm = T),
            total = sum(as.numeric(total), na.rm = T))%>%
  arrange(-total)
```

```{r}
events <- AGF_2014_19 %>%
  count(event) %>%
  ungroup() %>%
  filter(n > 1, event != "NA", event != "N/A") 

library(hrbrthemes)
# working so far
p <- AGF_2014_19 %>%
  semi_join(events, by="event") %>%
  mutate(year = year(date),
         event_date = as.numeric(format(date, "%j"))) %>%
  rename(trash_collected = total) %>%
  filter(year > 2014 & year < 2019) %>%
  filter(trash_collected > 0) %>%
  mutate(event = fct_reorder(event, event_date, min)) %>%
  ggplot(aes(x=event_date, y=event, colour = trash_collected, size = trash_collected, text = paste(paste0(city,","), date))) +
  scale_color_gradient2(low = "yellow", midpoint = 1000, mid = "orange", high = "dark red", na.value = "grey50") +
  geom_jitter(alpha = 0.7, shape = 21) +
  scale_x_continuous(breaks = c(0,31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334, 365), labels = c("Jan", "", "", "", "May", "", "", "", "Sept", "", "", "", "Dec")) +
  facet_wrap(~year, scales = "free_y", ncol=1) +
  ggthemes::theme_fivethirtyeight() +
  labs(title = "A Greener Future - Event Timeline",
       colour = "Trash Collected")

library(plotly)
q <- ggplotly(p, tooltip = c("y", "text", "colour"))
library(htmlwidgets)
saveWidget(q, "index.html", selfcontained = F)
```
Across Provinces (Ontario is only non-cigarette butt one)
```{r}
write_csv(AGF_2014_19, "AGF_2014_19.csv")
AGF_2014_19_long <- AGF_2014_19 %>%
  select(-total) %>%
  mutate(year = year(date)) %>%
  gather(Type, Count, -id, -date, -year, -longitude, -latitude, -location, -city, -province, -country, -photos, -sponsor, -event, -coordinator, -volunteers, -strange_items)
write_csv(AGF_2014_19, "AGF_2014_19_long.csv")
```


