---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
setwd(here::here())

tbl <- list.files(pattern = "^wellbeing") %>% 
    map_df(~read_csv(., col_types = cols(.default = "c")))

demographics_toronto <- read_csv("wellbeing-toronto-demographics.csv")
economy_toronto <- read_csv("wellbeing-toronto-economy.csv")
environment_toronto <- read_csv("wellbeing-toronto-environment.csv")
health_toronto <- read_csv( "wellbeing-toronto-health.csv")
population_toronto <- read_csv("wellbeing-toronto-population.csv")
youth_services_toronto <- read_csv("wellbeing-toronto-youth-services.csv")

wellbeing_toronto <- demographics_toronto %>%
  inner_join(environment_toronto %>% rename(neighbourhood_id = neighbourhood_id_new), by = "neighbourhood_id") %>%
  inner_join(health_toronto, by = "neighbourhood_id") %>%
  inner_join(population_toronto %>% select(neighbourhood_id, popchg11t16), by = "neighbourhood_id") %>%
  select(-neighbourhood.y, -neighbourhood) %>%
  rename(neighbourhood = neighbourhood.x)



  
  ###
  inner_join(youth_services_toronto %>% mutate(neighbourhood_id = ifelse(str_detect(neighbourhood, "[0-9]+$"),str_extract(neighbourhood, "[0-9]+$"), NA)) %>% drop_na(neighbourhood_id), by = "neighbourhood_id"))

```

```{r}
X2016_neighbourhood_profiles <- read_csv("2016_neighbourhood_profiles.csv")

topics <- c("Neighbourhood Number"
            ,"Population, 2016"
            ,"Population, 2011"
            ,"Population Change 2011-2016"
            ,"Total private dwellings"
            ,"Private dwellings occupied by usual residents"
            ,"Population density per square kilometre"
            ,"Land area in square kilometres"
            ,"Children (0-14 years)"
            ,"Youth (15-24 years)"
            ,"Working Age (25-54 years)"
            ,"Pre-retirement (55-64 years)"
            ,"Seniors (65+ years)"
            ,"Older Seniors (85+ years)"
            ,"Occupied private dwellings by structural type of dwelling"
            ,"Single-detached house"
            ,"Apartment in a building that has five or more storeys"
            ,"Other attached dwelling"
            ,"Semi-detached house"
            ,"Row house"
            ,"Apartment or flat in a duplex"
            ,"Apartment in a building that has fewer than five storeys"
            ,"Number of persons in private households"
            ,"Average household size"
            ,"Census families in private households by family size"
            ,86:89
            ,"Couples without children"
            ,"Couples with children"
            ,"Persons living alone (total)"
            ,"Single young adults (age 20-34) living at home (total)"
            ,"Total - Economic family income decile group for the population in private households - 100% data"
            ,"In the bottom half of the distribution"
            ,"In the top half of the distribution"
            ,"Total - Low-income status in 2015 for the population in private households to whom low-income concepts are applicable - 100% data"
            ,1120
            ,1122
            ,1123
            ,"Canadian citizens aged under 18"
            ,"Total - Generation status for the population in private households - 25% sample data"
            ,"First generation"
            ,"Second generation"
            ,"Third generation or more"
            ,"Total visible minority population"
            ,1334:1346
            ,"Total - Private households by tenure - 25% sample data"
            ,"Owner"
            ,"Renter"
            ,"Total - Occupied private dwellings by condominium status - 25% sample data"
            ,"Condominium"
            ,"Not condominium"
            ,"Total - Occupied private dwellings by period of construction - 25% sample data"
            ,1652:1658
            ,"Rate of unaffordable housing"
            ,"Total population aged 15 years and over by work activity during the reference year - 25% sample data"
            ,"Did not work"
            ,"Worked"
            ,"Worked full year, full time"
            ,"Worked part year and/or part time")








	










augment_data <- X2016_neighbourhood_profiles %>%
  select(Characteristic, 6:145) %>%
  gather(Neighbourhood, value, -Characteristic) %>% 
  filter(Characteristic %in% topics) %>%
  spread(Characteristic, value) %>%
  janitor::clean_names()


 augment_data %>%
  filter(neighbourhood == "Harbourfront")
 
library(rvest)
neighbourhoods <- read_html("https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M") %>% html_node('table') %>% html_table() %>% rename(neighbourhood = Neighbourhood)

augment_data %>% select(neighbourhood)
neighbourhoods<- neighbourhoods %>% select(1,3) %>% filter(neighbourhood != "Not assigned") %>% mutate(neighbourhood = str_remove_all(neighbourhood, "^The ")) %>% arrange(neighbourhood) %>% 
  mutate(neighbourhoods =
           case_when(
             "Agincourt South-Malvern West" ~ "Malvern",
             "Banbury-Don Mills" ~ "Don Mills North", # missing don mills south
             "Bayview Woods-Steeles" ~ "South Steeles", # missing steeles east
             "Bedford Park-Nortown" ~ "Bedford Park",

           ))
# MIA Bay Street Corridor
# MIA Beechborough-Greenbrook-

donations <- read_csv("full_set_with_targets.csv") 
donations %>%
  select(FSA) %>%
  filter(str_detect(FSA, "^M")) %>%
  count(FSA) %>%
  filter(n > 10) %>%
  arrange(desc(FSA))


joined <- augment_data %>%
  inner_join(neighbourhoods, by= "neighbourhood") %>%
  inner_join(donations, by=c("Postcode" = "FSA")) 

joined %>% View()
```

Commuting
```{r}

c("Total - Main mode of commuting for the employed labour force aged 15 years and over in private households with a usual place of work or no fixed workplace address - 25% sample data"
,"Car, truck, van - as a driver"
,"Car, truck, van - as a passenger"
,"Public transit"
,"Walked"
,"Bicycle"
,"Other method"
,"Total - Commuting duration for the employed labour force aged 15 years and over in private households with a usual place of work or no fixed workplace address - 25% sample data"
,"Less than 15 minutes"
,"15 to 29 minutes"
,"30 to 44 minutes"
,"45 to 59 minutes"
,"60 minutes and over"
,"Total - Time leaving for work for the employed labour force aged 15 years and over in private households with a usual place of work or no fixed workplace address - 25% sample data"
,"Between 5 a.m. and 5:59 a.m."
,"Between 6 a.m. and 6:59 a.m."
,"Between 7 a.m. and 7:59 a.m."
,"Between 8 a.m. and 8:59 a.m."
,"Between 9 a.m. and 11:59 a.m."
,"Between 12 p.m. and 4:59 a.m.",
,"Employment income: Average amount ($)"

)






```

```{r}
economy_toronto %>%
  rename(neighbourhood_id = neighbourhood_id_fixed) %>%
  inner_join(demographics_toronto, by=c("neighbourhood_id", "neighbourhood")) %>%
  filter(neighbourhood_id %in% c("065", "067", "058")) %>%
  select(-local_employment, -pop_males, -pop_females) %>%
  mutate(business_per_capita = businesses/total_population,
         children_per_childcare = (pop_0_4_years + pop_5_9_years)/child_care_spaces,
         neighbourhood_home_score = social_assistance_recipients/home_prices,
         childcare_rating = child_care_spaces*(pop_0_4_years + pop_5_9_years)/total_population) %>%
  select(child_care_spaces, children_per_childcare, childcare_rating, pop_0_4_years, pop_5_9_years, total_population)

economy_toronto %>%
  rename(neighbourhood_id = neighbourhood_id_fixed) %>%
  inner_join(demographics_toronto, by=c("neighbourhood_id", "neighbourhood")) %>%
  select(-local_employment, -pop_males, -pop_females) %>%
  mutate(business_per_capita = businesses/total_population,
         children_per_childcare = (pop_0_4_years + pop_5_9_years)/child_care_spaces,
         neighbourhood_home_score = social_assistance_recipients/home_prices,
         childcare_rating = child_care_spaces*(pop_0_4_years + pop_5_9_years)/total_population) %>%
  filter(child_care_spaces > 0) %>%
  filter(total_population < 20000) %>%
  select(children_per_childcare) %>%
  summarize(avg_child_per_childcare = mean(children_per_childcare))
```

```{r}

```

```{r}

```





```{r}

remove_culture <- names(wellbeing_toronto[,c(1:25,41:101)])
gather_1 <- wellbeing_toronto %>%
  filter(neighbourhood_id %in% c("065", "067", "058")) %>%
  gather(culture, wellbeing_toronto[,26:40], -remove_culture)


remove_populations <- names(gather_1[,c(1:3, 26:88)])
gather_2 <- gather_1 %>%
  gather(populations, gather_1[,4:25], -remove_populations)


remove_languages <- names(gather_2[,c(1:3, 15:68)])
gather_3 <- gather_2 %>%
  gather(languages, gather_2[,4:14], -remove_languages)

remove_migration <- names(gather_3[,c(1:3, 16:56)])
gather_4 <- gather_3 %>%
  select(1:3,7:59) %>%
  gather(migration, gather_3[,4:15], -remove_migration)

remove_labour <- names(gather_4[,c(1:3, 8:46)])
gather_5 <- gather_4 %>%
  gather(labour, gather_4[4:7], -remove_labour)
  
remove_education <- names(gather_5[,c(1:3, 7:44)])
gather_6 <- gather_5 %>%
  gather(education, gather_5[4:6], -remove_education)

remove_residence <- names(gather_6[,c(1:3, 11:42)])
gather_7 <- gather_6 %>%
  gather(residence_status, gather_6[4:10], -remove_residence)

remove_income <- names(gather_7[,c(1:3, 11:37)])
gather_8 <- gather_7 %>%
  gather(income, gather_7[4:10], -remove_income)

```

