---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(lubridate)
```
# loading and renaming vars
```{r}
donations <- read_csv("donations.CSV")
names(donations) <- c("unique_donation_id", "gf_date", "gf_amount", "donation_approach", "donation_designation", "gf_type", "unique_constituent_id")

constituents <- read_csv("Constituents0416.CSV")
names(constituents) <- c("unique_constituent_id", "key_indicator", "gender", "postal_code", "first_gift_amnt", "first_gift_date", "last_gift_amount", "last_gift_date", "largest_gift_amount", "largest_gift_date")

volunteer <- read_csv("Volunteer.csv")
names(volunteer) <- c("unique_constituent_id", "activity", "total_hours", "assignment_date")
```

# creating subsets for is_donar
```{r}
# is_donor targets
(volunteers_who_are_donors <- donations %>%
  inner_join(volunteer) %>%
  count(unique_constituent_id))
# 365/1022 volunteers have donated
# ~33%
(constituents_who_are_donors <- donations %>%
  inner_join(constituents) %>%
  count(unique_constituent_id))
# 8368 / 10405 constituents donated
# ~80%
```

# creating long_term donors (more than 5 donations)
```{r}
(termed_volunteer_donors <- donations %>%
  inner_join(volunteer) %>%
  count(unique_constituent_id) %>%
  filter(n>=5))
# 216/365 of volunteers who have donated are "long_term"
# ~60%

(termed_constituent_donors <- donations %>%
  inner_join(constituents) %>%
  count(unique_constituent_id) %>%
  filter(n>=5))
# 1290 / 8371 of constiuents who have donated are "long_term"
# ~15%

# volunteers are likelier to be long-term compared to regular constituents
```
# cleaning and creating target vars
```{r}
unique_volunteer_set <- volunteer %>%
  mutate(volunteer_date = mdy_hms(assignment_date)) %>%
  group_by(unique_constituent_id) %>%
  mutate(date_became_volunteer = min(volunteer_date),
         total_hours = sum(total_hours),
         volunteer_events = as.numeric(n())) %>%
  rename(volunteer_hours = total_hours) %>%
  left_join(donations %>% mutate(gf_date = mdy(gf_date))) %>%
  select(unique_constituent_id, date_became_volunteer, gf_date, gf_amount, volunteer_events, volunteer_hours) %>%
  group_by(unique_constituent_id) %>%
  mutate(gf_date = min(gf_date)) %>%
  mutate(days_since_volunteering = gf_date - ymd(date_became_volunteer),
         is_volunteer_before_donating = ifelse(days_since_volunteering > 0 , 1 , 0),
         date_became_volunteer = ymd(date_became_volunteer)) %>%
  ungroup() %>%
  select(-gf_amount, - gf_date, -days_since_volunteering) %>%
  mutate(is_volunteer_before_donating = ifelse(is.na(is_volunteer_before_donating), 0, is_volunteer_before_donating)) %>%
  unique()

# need to remove specific events so volunteers can join without making multiple unique_donation_ids... so I summed up total hours and number of events
unique_volunteer_set <- volunteer %>%
  select(-activity, -assignment_date) %>%
  group_by(unique_constituent_id) %>%
  mutate(total_hours = sum(total_hours),
         volunteer_events = as.numeric(n())) %>%
  rename(volunteer_hours = total_hours) %>%
  ungroup() %>%
  unique()
```

# joining
```{r}
constituents_target <- constituents %>%
  left_join(donations) %>%
  left_join(unique_volunteer_set) %>%
  
# cleaning var-types and extracting numerics
  mutate(gf_date = mdy(gf_date),
        
         gf_amount = as.numeric(str_remove_all(gf_amount, "[$,]")),
         
         first_gift_amnt = as.numeric(str_remove_all(first_gift_amnt, "[$,]")),
         
         first_gift_date = mdy(first_gift_date),
         
         largest_gift_amount = as.numeric(str_remove_all(largest_gift_amount, "[$,]")),
         
         largest_gift_date = mdy(largest_gift_date),
         
         last_gift_amount = as.numeric(str_remove_all(last_gift_amount, "[$,]")),
         
         last_gift_date = mdy(last_gift_date),
         
         FSA = str_extract(postal_code, "^[A-Za-z][0-9][A-Za-z]"),
         
         key_indicator = case_when(
           key_indicator == "I" ~ "Individual",
           key_indicator == "O" ~ "Organization"
         )) %>%

# target vars
  mutate(
         is_volunteer = ifelse(unique_constituent_id %in% volunteer$unique_constituent_id, 1, 0),
         
         is_constituent = ifelse(unique_constituent_id %in% constituents$unique_constituent_id, 1, 0),
        
         is_donor = ifelse(unique_constituent_id %in% volunteers_who_are_donors$unique_constituent_id | unique_constituent_id %in% constituents_who_are_donors$unique_constituent_id, 1, 0),
    
         volunteer_events = case_when(
           is.na(volunteer_events) ~ 0,
           TRUE ~ volunteer_events),
         
         volunteer_hours = case_when(
           is.na(volunteer_hours) ~ 0,
           TRUE ~ volunteer_hours)) %>%
  select(-postal_code, -gender)
  

######  
  donation_designation = case_when(
           str_detect(donation_designation, "^GIK") ~ "Gifts in Kind",
           TRUE ~ donation_designation)) %>%
  mutate(donation_designation = fct_lump(donation_designation, 3))

# this dataset is missing the event type and hours per event each volunteer so it can join correctly. it is replaced by total events and total hours.

write_csv(constituents_target, "full_set_with_targets.csv")
```

```{r}
updates <- read_csv("~/DataForGood_Yes/full_set_with_targets.csv")

# creating times donated --- LOOK AT REMOVING SINGLE TIME DONORS FROM SET
times_donated <- updates %>%
  group_by(unique_constituent_id) %>%
  count() %>%
  rename(times_donated = n)

# creating average donation
avg_donation <- updates %>%
  rename(donor_since = first_gift_amnt) %>%
  group_by(unique_constituent_id) %>%
  summarize(avg_donation = round(mean(gf_amount),2))

updates <- updates %>%
  group_by(unique_constituent_id) %>%
  mutate(length_of_donor_relationship = max(gf_date) - min(gf_date)) %>% 
  ungroup() %>%
  inner_join(times_donated) %>%
  inner_join(avg_donation) %>%
  rename(donor_since = first_gift_date) %>%
  mutate(donor_since = year(donor_since)) 


# 
final <- updates %>%
  select(-unique_donation_id, -gf_date, -gf_amount, -largest_gift_amount, -donation_approach, -donation_designation, -gf_type, -largest_gift_date, -is_donor, - is_constituent) %>%
    unique() %>% mutate(churned = ifelse(last_gift_date < as.Date("2018-01-01"), 1, 0), last_gift_date = year(last_gift_date))

final
model <- glm(data = final %>% select(-volunteer_events, -unique_constituent_id, -volunteer_hours, -FSA, -became_volunteer, -volunteer_before_donating), is_volunteer ~ ., family = "binomial")
library(broom)



lm(times_donated ~ ., data = final %>% select(-FSA)) %>% tidy %>% filter(p.value < 0.05)

lm(volunteer_hours ~ ., data = final %>% select(-FSA)) %>% tidy %>% filter(p.value < 0.05)



tidy(model) %>% filter(!str_detect(term, "^FSA"), p.value < 0.05)

# see influences!
model %>%
  tidy() %>%
  filter(term != "(Intercept)") %>%
  mutate(term = reorder(term, estimate)) %>%
  ggplot(aes(x=estimate, y= term)) +
  geom_point()

# show the break of positive negative
model %>%
  tidy() %>%
  mutate(term = reorder(term, estimate)) %>%
  ggplot(aes(x=estimate, y= term)) +
  geom_point() +
  geom_vline(xintercept = 0, color = "red", lty = 2)
```

```{r}
library(survival)


dolphin_survival <- final %>%
  mutate(churnYear = ifelse(churned == 1, last_gift_date, first_gift_date),
         age = churnYear - first_gift_date) %>%
  filter(churnYear >= first_gift_date) %>%
  select(age, churned, is_volunteer) 


# require some data prep USING YEARS
dolphin_survival <- final %>%
  mutate(churnYear = ifelse(churned == 1, last_gift_date, first_gift_date),
         age = churnYear - first_gift_date) %>%
  filter(!is.na(churnYear)) %>%
  select(first_gift_date, churnYear, age, churned, is_volunteer, times_donated) %>%
  filter(churnYear >= first_gift_date)

model <- survfit(Surv(age, churned) ~ 1, dolphin_survival)
model

library(broom)

tidy(model) %>%
  ggplot(aes(x=time, y=estimate)) +
  geom_line() +
  geom_ribbon(aes(ymin=conf.low, ymax = conf.high), alpha=.2) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(y = "Estimated % of Survival",
       x = "Time (in years)") +
  labs(title = "Donor Survival Analysis",
       subtitle = "Median life expectancy is 6 years")

survfit(Surv(age, churned) ~ 1, dolphin_survival)

```

```{r}
model <- survfit(Surv(age, churned) ~ is_volunteer, dolphin_survival)

tidy(model) %>%
  ggplot(aes(x=time, y=estimate, colour = strata)) +
  geom_line() +
  geom_ribbon(aes(ymin=conf.low, ymax = conf.high), alpha=.2) +
  scale_y_continuous(labels = scales::percent_format()) +
  labs(y = "Estimated % of Survival")

survfit(Surv(age, churned) ~ is_volunteer, dolphin_survival)

# seems close, is there a significant difference?
coxph(Surv(age, churned) ~ is_volunteer, dolphin_survival)


coxph(Surv(age, churned) ~ is_volunteer, dolphin_survival) %>%
  tidy()
```




```{r}
library(caret)
set.seed(825)


# preProc = c("center", "scale")

# data split 75% train - 25% validate
index_train <- sample(1:nrow(final), 3/4 * nrow(final))
training <- final[index_train, ]
validation <- final[-index_train, ]

fitControl <- trainControl(## 10-fold CV
                           method = "repeatedcv",
                           number = 10,
                           ## repeated ten times
                           repeats = 10)

gbmGrid <-  expand.grid(interaction.depth = c(1, 5, 9), 
                        n.trees = (1:30)*50, 
                        shrinkage = 0.1,
                        n.minobsinnode = 20)



gbmFit1 <- train(churned ~ ., data = training %>% select(-volunteer_before_donating, -became_volunteer), 
                 method = "gbm", 
                 trControl = fitControl,
                 ## This last option is actually one
                 ## for gbm() that passes through
                 verbose = FALSE,
                 tuneGrid = gbmGrid)

gbmFit1

gbmFit1_pred <- predict(gbmFit1, newdata=validation,  type = "prob")
  gbmFit1_pred_cutoff_50 <- ifelse( gbmFit1_pred[,2] > 0.5, 1,0)
  fit.gbm_conf_matrix_50 <- table(validation$churned, gbmFit1_pred_cutoff_50) %>% confusionMatrix()
fit.gbm_conf_matrix_50


fitControl3 <- trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10,
                           ## Estimate class probabilities
                           classProbs = TRUE,
                           ## Evaluate performance using 
                           ## the following function
                           summaryFunction = twoClassSummary)

set.seed(825)
gbmFit3 <- train(Class ~ ., data = training, 
                 method = "gbm", 
                 trControl = fitControl3, 
                 verbose = FALSE, 
                 tuneGrid = gbmGrid,
                 ## Specify which metric to optimize
                 metric = "ROC")
gbmFit3

gbmFit3_pred <- predict(gbmFit3, newdata=validation,  type = "prob")
  gbmFit3_pred_cutoff_50 <- ifelse( gbmFit3_pred[,2] > 0.5, 1,0)
  fit.gbm3_conf_matrix_50 <- table(validation$churned, gbmFit3_pred_cutoff_50) %>% confusionMatrix()
fit.gbm3_conf_matrix_50

```

```{r}
set.seed(825)
svmFit <- train(cjirmed ~ ., data = training, 
                 method = "svmRadial", 
                 trControl = fitControl, 
                 preProc = c("center", "scale"),
                 tuneLength = 8,
                 metric = "ROC")
svmFit   

rdaFit <- train(Class ~ ., data = training, 
                 method = "rda", 
                 trControl = fitControl, 
                 tuneLength = 4,
                 metric = "ROC")
rdaFit      



resamps <- resamples(list(GBM = gbmFit3,
                          SVM = svmFit,
                          RDA = rdaFit))
summary(resamps)
```

